### ISSUE TITLE
Ui not loaded from .ui file 

### ISSUE THREAD

**Issue by orensbruli** [ARebollo/ArtificialVision#3]
I think that the UI code of the Master branch have been copied and pasted from the autogenerated (pyuic) .py file. Is that right?
I think we could use a dynamic method to do this. PyQt have the uic module and loadUI which can be used to load .ui files and assign those UI items to a designated widget (it can be self or whatever you want). Here you can see some examples: https://www.programcreek.com/python/example/96001/PyQt5.uic.loadUi
In this way we could use the supplied .ui files on each practice.
What do you think?

**Comment by orensbruli** [comment]
Please review the code on the 0_BaseProject branch. It's loading all the interface from the .UI
https://github.com/ARebollo/ArtificialVision/tree/0_BaseProject
I think it can be used for all the future projects changing the mainwindow.ui or following the same steps for new widgets defined on other .ui files.

**Comment by ARebollo** [comment]
We had the same approach, it's in the latest branch, being worked on at this moment for the second iteration of the project. It follows the same scheme: loading the file first, then adding additional objects and connecting the buttons to functions.
